kampanile3/gpio/urls.py
from django.urls import include, path

from . import views

app_name = "gpio"
urlpatterns = [
    path(
        "inputs/",
        include(
            (
                [
                    path("", views.InputListView.as_view(), name="list"),
                    path("add/", views.InputCreateView.as_view(), name="add"),
                    path("<int:pk>/", views.InputDetailView.as_view(), name="detail"),
                    path(
                        "<int:pk>/update/",
                        views.InputUpdateView.as_view(),
                        name="update",
                    ),
                    path(
                        "<int:pk>/delete/",
                        views.InputDeleteView.as_view(),
                        name="delete",
                    ),
                ],
                "inputs",
            )
        ),
    )
]

kampanile3/kampanile3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("frontend.urls")),
    path("carillon/", include("carillon.urls")),
    path("gpio/", include("gpio.urls")),
]

kampanile3/gpio/models.py
import digitalio
import microcontroller
from carillon.models import Striker
from django.db import models
from django.db.models import Q, UniqueConstraint
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from .signals import input_triggered


class Input(models.Model):
    """A model representing a GPIO-input that can trigger a striker."""

    class Behaviour(models.TextChoices):
        """Setting on what input action should call the trigger."""

        ON_INPUT_LOW = "L", _("On input state low")
        ON_INPUT_HIGH = "H", _("On input state high")
        ON_INPUT_CHANGE = "C", _("On change of input state")

    class Pull(models.TextChoices):
        """Setting for the internal pull resistor of the input pin."""

        NONE = "N", _("No pull resistor")
        UP = "U", _("Pull-up resistor")
        DOWN = "D", _("Pull-down resistor")

    name = models.CharField(
        max_length=255,
        verbose_name=_("Name"),
    )
    """The name of the input for a friendly display."""

    pin = models.CharField(
        max_length=10,
        verbose_name=_("I/O-Pin"),
        blank=True,
        default="",
    )
    """The GPIO pin name as provided by the Adafruit Blinka library."""

    active = models.BooleanField(
        default=True,
        verbose_name=_("Active"),
        help_text=_("Whether this input is active and should be monitored."),
    )
    """Whether this input is active and should be monitored."""

    error = models.CharField(
        max_length=255,
        verbose_name=_("Error"),
        blank=True,
        default="",
        help_text=_(
            "An error message if there is an issue with this input. Will be cleared when the input is set active."
        ),
    )
    """An error message if there is an issue with this input."""

    pull = models.CharField(
        max_length=1,
        choices=Pull,
        default=Pull.NONE,
        verbose_name=_("Pull resistor"),
        help_text=_("The internal pull resistor for the input pin."),
    )
    """The internal pull resistor setting for the input pin."""

    debounce = models.BooleanField(
        default=True,
        verbose_name=_("Debounce"),
        help_text=_("Whether to apply debouncing to the input signal."),
    )
    """Whether to apply debouncing to the input signal."""

    deadtime = models.PositiveIntegerField(
        default=0,
        verbose_name=_("Deadtime (ms)"),
        help_text=_(
            "Time after a trigger during which no new triggers will be accepted."
        ),
    )
    """Time after a trigger during which no new triggers will be accepted."""

    striker = models.ForeignKey(
        Striker,
        on_delete=models.CASCADE,
        verbose_name=_("Striker"),
        related_name="+",
        blank=True,
        null=True,
    )
    """The striker that should be triggered by this input."""

    behaviour = models.CharField(
        max_length=1,
        choices=Behaviour,
        default=Behaviour.ON_INPUT_CHANGE,
        verbose_name=_("Behaviour"),
        help_text=_("Which trigger should call the striker?"),
    )
    """The behaviour for triggering this input."""

    def trigger(self):
        """Trigger the striker associated with this input."""
        input_triggered.send(sender=self.__class__, input=self)
        self.striker.check_rules()

    def get_absolute_url(self):
        return reverse("gpio:inputs:detail", kwargs={"pk": self.pk})

    def deactivate(self, error: str):
        """Deactivate this input with an error message."""
        self.error = error
        self.active = False
        self.save()

    @property
    def board_pin(self):
        import board

        if not self.pin or not hasattr(board, self.pin):
            return None
        pin = getattr(board, self.pin)
        if not isinstance(pin, microcontroller.Pin):
            return None
        return pin

    @property
    def pull_setting(self):
        if self.pull == self.Pull.UP:
            return digitalio.Pull.UP
        if self.pull == self.Pull.DOWN:
            return digitalio.Pull.DOWN
        return None

    def save(self, *args, **kwargs):
        if self.active and self.error:
            self.error = ""
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = _("Input")
        verbose_name_plural = _("Inputs")
        ordering = ["pin"]
        constraints = [
            UniqueConstraint(
                fields=["pin"],
                condition=Q(active=True) & ~Q(pin=""),
                name="unique_active_pin",
            )
        ]

kampanile3/gpio/forms.py
import microcontroller
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Field, Layout
from django import forms
from django.urls import reverse
from frontend.forms import FormAction

from .models import Input


def get_board_pins():
    import board

    yield ("", "---------")
    for pin in dir(board):
        if isinstance(getattr(board, pin), microcontroller.Pin):
            yield (pin, pin)


class InputForm(forms.ModelForm):
    """This form allows the user to select a board pin from available pins."""

    pin = forms.ChoiceField(
        widget=forms.Select,
        choices=get_board_pins,
        required=False,
    )

    class Meta:
        model = Input
        fields = [
            "name",
            "pin",
            "active",
            "pull",
            "debounce",
            "deadtime",
            "striker",
            "behaviour",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = "form-horizontal"
        self.helper.label_class = "col-sm-2"
        self.helper.field_class = "col-sm-10"
        if self.instance.pk:
            url = self.instance.get_absolute_url()
        else:
            url = reverse("gpio:inputs:list")
        self.helper.layout = Layout(
            Field("name"),
            Field("pin"),
            Field("active"),
            Field("pull"),
            Field("debounce"),
            Field("deadtime"),
            Field("striker"),
            Field("behaviour"),
            FormAction(cancel_url=url),
        )

kampanile3/gpio/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .forms import InputForm
from .models import Input


class InputListView(LoginRequiredMixin, ListView):
    model = Input

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "title": _("Inputs"),
                "subtitle": _("The following inputs are configured for this board:"),
            }
        )
        return context


class InputDetailView(LoginRequiredMixin, DetailView):
    model = Input

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "back_link": reverse("gpio:inputs:list"),
                "title": _("Input: %(name)s") % {"name": self.object.name},
            }
        )
        return context


class InputCreateView(LoginRequiredMixin, CreateView):
    model = Input
    form_class = InputForm
    template_name = "frontend/simple_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "back_link": reverse("gpio:inputs:list"),
                "title": _("Create input"),
                "subtitle": _("Add a GPIO input to trigger a striker."),
            }
        )
        return context


class InputUpdateView(LoginRequiredMixin, UpdateView):
    model = Input
    form_class = InputForm
    template_name = "frontend/simple_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "back_link": self.object.get_absolute_url(),
                "title": _("Update GPIO input"),
                "subtitle": self.object.name,
            }
        )
        return context


class InputDeleteView(LoginRequiredMixin, DeleteView):
    model = Input
    template_name = "frontend/confirm_delete.html"

    def get_success_url(self):
        return reverse("gpio:inputs:list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "back_link": reverse("gpio:inputs:list"),
                "title": _("Delete GPIO input"),
                "subtitle": _(
                    'Are you sure you want to delete the GPIO input "%(name)s"?'
                )
                % {"name": self.object.name},
            }
        )
        return context

kampanile3/gpio/templates/gpio/input_detail.html
{% extends "frontend/base.html" %}
{% load i18n static %}

{% block content %}
  {% url "gpio:inputs:update" input.pk as url %}
  {% include "frontend/includes/update_button.html" with label=_("Update input") %}

  <dl class="row mt-3">
    <dt class="col-sm-3">{% trans "Pin" %}</dt>
    <dd class="col-sm-9">
      {% if input.pin %}
        <code>{{ input.pin }}</code> ({{ input.board_pin.id }})
      {% else %}
        <em>
          {% blocktrans %}This input is not connected to a pin.{% endblocktrans %}
        </em>
      {% endif %}
    </dd>

    <dt class="col-sm-3">{% trans "Active" %}</dt>
    <dd class="col-sm-9">
      {% if input.active %}
        <span class="mdi mdi-check" title="{% translate "Active" %}" data-bs-toggle="tooltip"></span>
      {% else %}
        <span class="mdi mdi-close" title="{% translate "Inactive" %}" data-bs-toggle="tooltip"></span>
      {% endif %}
    </dd>

    {% if input.error %}
      <dt class="col-sm-3">{% trans "Error" %}</dt>
      <dd class="col-sm-9 text-danger">{{ input.error }}</dd>
    {% endif %}

    <dt class="col-sm-3">{% trans "Pull resistor" %}</dt>
    <dd class="col-sm-9">{{ input.get_pull_display }}</dd>

    <dt class="col-sm-3">{% trans "Striker" %}</dt>
    <dd class="col-sm-9">
      {% if input.striker %}
        <a href="{{ input.striker.get_absolute_url }}">{{ input.striker.name }}</a>
      {% else %}
        <em>
          {% blocktrans %}This input is not connected to a striker.{% endblocktrans %}
        </em>
      {% endif %}
    </dd>

    <dt class="col-sm-3">{% trans "Behaviour" %}</dt>
    <dd class="col-sm-9">{{ input.get_behaviour_display }}</dd>
  </dl>
{% endblock %}

kampanile3/gpio/templates/gpio/input_list.html
{% extends "frontend/base.html" %}
{% load i18n %}

{% block content %}
  {% url "gpio:inputs:add" as url %}
  {% include "frontend/includes/add_button.html" with label=_("Add input") %}

  <table class="table">
    <thead>
      <tr>
        <th scope="col">
          <span class="mdi mdi-connection" title="{% trans "Input active?" %}" data-bs-toggle="tooltip"></span>
        </th>
        <th scope="col" class="w-50">{% trans "Name" %}</th>
        <th scope="col" colspan="2">{% trans "Pin" %}</th>
        <th scope="col">
          <span class="mdi mdi-resistor" title="{% trans "Pull resistor?" %}" data-bs-toggle="tooltip"></span>
        </th>
        <th scope="col" class="w-25">{% trans "Striker" %}</th>
        <th scope="col" class="w-25">{% trans "Behaviour" %}</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {% for input in input_list %}
        <tr>
          <td>
            {% if input.active %}
              <span class="mdi mdi-check" title="{% translate "Active" %}" data-bs-toggle="tooltip"></span>
            {% else %}
              <span class="mdi mdi-close" title="{% translate "Inactive" %}" data-bs-toggle="tooltip"></span>
            {% endif %}
          </td>
          <th scope="row">
            <a href="{{ input.get_absolute_url }}">{{ input.name }}</a>
            {% if input.error %}
              <span class="mdi mdi-alert-circle-outline text-danger" title="{{ input.error }}" data-bs-toggle="tooltip"></span>
            {% endif %}
          </th>
          <td><code>{{ input.pin }}</code></td>
          <td>
            {% if input.board_pin %}
              <small class="text-muted">({{ input.board_pin.id }})</small>
            {% endif %}
          </td>
          <td>
            <span
              class="mdi mdi-{% if input.pull == input.Pull.UP %}arrow-up-bold{% elif input.pull == input.Pull.DOWN %}arrow-down-bold{% else %}minus{% endif %}"
              title="{{ input.get_pull_display }}"
              data-bs-toggle="tooltip"
            ></span>
          </td>
          <td>
            {% if input.striker %}
              <a href="{{ input.striker.get_absolute_url }}">{{ input.striker.name }}</a>
            {% else %}
              <span class="text-muted">{% trans "No striker assigned" %}</span>
            {% endif %}
          </td>
          <td>{{ input.get_behaviour_display }}</td>
          <td class="text-nowrap">
            {% url "gpio:inputs:update" input.pk as update_url %}
            {% url "gpio:inputs:delete" input.pk as delete_url %}
            {% include "frontend/includes/table_btn_group.html" with view_url=input.get_absolute_url %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}