kampanile3/carillon/urls.py
from django.urls import include, path

from .views import carillon, song, striker

app_name = "carillon"
urlpatterns = [
    path(
        "carillons/",
        include(
            (
                [
                    path("", carillon.CarillonListView.as_view(), name="list"),
                    path("add/", carillon.CarillonCreateView.as_view(), name="add"),
                    path(
                        "<int:pk>/",
                        carillon.CarillonDetailView.as_view(),
                        name="detail",
                    ),
                    path(
                        "<int:pk>/update/",
                        carillon.CarillonUpdateView.as_view(),
                        name="update",
                    ),
                    path(
                        "<int:pk>/delete/",
                        carillon.CarillonDeleteView.as_view(),
                        name="delete",
                    ),
                    path("<int:pk>/hit/", carillon.hit_note_view, name="hit_note"),
                    path("<int:pk>/stop/", carillon.stop_view, name="stop"),
                    path(
                        "<int:pk>/set-volume/",
                        carillon.set_volume_view,
                        name="set_volume",
                    ),
                    path(
                        "<int:pk>/set-default/",
                        carillon.set_default_view,
                        name="set_default",
                    ),
                    path(
                        "<int:pk>/toggle-active/",
                        carillon.toggle_active_view,
                        name="toggle_active",
                    ),
                ],
                "carillons",
            )
        ),
    ),
    path(
        "songs/",
        include(
            (
                [
                    path("", song.SongListView.as_view(), name="list"),
                    path("add/", song.SongCreateView.as_view(), name="add"),
                    path("<int:pk>/", song.SongDetailView.as_view(), name="detail"),
                    path(
                        "<int:pk>/update/", song.SongUpdateView.as_view(), name="update"
                    ),
                    path(
                        "<int:pk>/delete/", song.SongDeleteView.as_view(), name="delete"
                    ),
                    path("<int:pk>/play/", song.play_view, name="play"),
                ],
                "songs",
            )
        ),
    ),
    path(
        "strikers/",
        include(
            (
                [
                    path("", striker.StrikerListView.as_view(), name="list"),
                    path("add/", striker.StrikerCreateView.as_view(), name="add"),
                    path(
                        "<int:pk>/", striker.StrikerDetailView.as_view(), name="detail"
                    ),
                    path(
                        "<int:pk>/update/",
                        striker.StrikerUpdateView.as_view(),
                        name="update",
                    ),
                    path(
                        "<int:pk>/delete/",
                        striker.StrikerDeleteView.as_view(),
                        name="delete",
                    ),
                    path(
                        "<int:pk>/add-rule/",
                        striker.StrikerRuleCreateView.as_view(),
                        name="add_rule",
                    ),
                ],
                "strikers",
            ),
        ),
    ),
    path(
        "strikers/rules/",
        include(
            (
                [
                    path(
                        "<int:pk>/",
                        striker.StrikerRuleDetailView.as_view(),
                        name="detail",
                    ),
                    path(
                        "<int:pk>/update/",
                        striker.StrikerRuleUpdateView.as_view(),
                        name="update",
                    ),
                    path(
                        "<int:pk>/delete/",
                        striker.StrikerRuleDeleteView.as_view(),
                        name="delete",
                    ),
                ],
                "rules",
            )
        ),
    ),
]

kampanile3/gpio/urls.py
from django.urls import include, path

from . import views

app_name = "gpio"
urlpatterns = [
    path(
        "inputs/",
        include(
            (
                [
                    path("", views.InputListView.as_view(), name="list"),
                    path("add/", views.InputCreateView.as_view(), name="add"),
                    path("<int:pk>/", views.InputDetailView.as_view(), name="detail"),
                    path(
                        "<int:pk>/update/",
                        views.InputUpdateView.as_view(),
                        name="update",
                    ),
                    path(
                        "<int:pk>/delete/",
                        views.InputDeleteView.as_view(),
                        name="delete",
                    ),
                ],
                "inputs",
            )
        ),
    )
]

kampanile3/kampanile3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("frontend.urls")),
    path("carillon/", include("carillon.urls")),
    path("gpio/", include("gpio.urls")),
]

kampanile3/carillon/models/rule.py
import mido
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from .conditions import build_condition
from .song import Song
from .striker import Striker


def validate_rule_condition(value):
    build_condition(value).validate()


class Rule(models.Model):
    """A rule that defines when and what a striker should play."""

    class RepeatSettings(models.TextChoices):
        """Settings for how often the played song should be repeated."""

        OFF = "o", _("Off")
        HOURS12 = "h12", _("For every hour once 12-based")
        HOURS24 = "h24", _("For every hour once 24-based")
        MINUTES15 = "m15", _("For every 15 minutes")
        MINUTES30 = "m30", _("For every 30 minutes")

    name = models.CharField(max_length=255, verbose_name=_("Name"))
    """The name of the rule for a friendly display."""

    striker = models.ForeignKey(
        Striker,
        on_delete=models.CASCADE,
        verbose_name=_("Striker"),
        help_text=_("The striker that checks, if the rule applies."),
        related_name="rules",
    )
    """The striker that checks if the rule applies."""

    priority = models.SmallIntegerField(
        default=0,
        verbose_name=_("Priority"),
        help_text=_("The priority of the rule. Higher values means firstly evaluated."),
    )
    """The priority of the rule, used to determine the order of evaluation."""

    cancel_following = models.BooleanField(
        default=False,
        verbose_name=_("Cancel following rules"),
        help_text=_(
            "If checked, no following rule with smaller priority will be executed if this rule applies."
        ),
    )
    """Whether to cancel following rules with smaller priority."""

    condition = models.JSONField(
        verbose_name=_("Condition"),
        help_text=_("A JSON object actually defining the condition."),
        default=dict,
        blank=True,
        validators=[validate_rule_condition],
    )
    """The JSON object describing the condition for the rule."""

    song = models.ForeignKey(
        Song,
        on_delete=models.RESTRICT,
        verbose_name=_("Song"),
        help_text=_("The song to play when the rule applies."),
        related_name="+",
        blank=True,
        null=True,
    )
    """The song to play when the rule applies. None is allowed for rules that abort playing sounds."""

    repeat = models.CharField(
        max_length=3,
        choices=RepeatSettings,
        default=RepeatSettings.OFF,
        verbose_name=_("Repeat"),
        help_text=_(
            "How often the played song should be repeated if the rule applies."
        ),
    )
    """The song can optionally be repeated based on the selected setting."""

    @property
    def parsed_condition(self):
        """Return the parsed condition object."""
        return build_condition(self.condition)

    @property
    def is_met(self):
        """Check if the condition of this rule is met."""
        return self.parsed_condition.is_met

    @property
    def number_repeats(self) -> int:
        """
        Returns the number of times the song should be played when the rule
        applies, taking into account the repeat setting.
        """
        repeats = 1
        now = timezone.localtime()
        if self.repeat == Rule.RepeatSettings.HOURS12:
            repeats = now.hour % 12 or 12
        elif self.repeat == Rule.RepeatSettings.HOURS24:
            repeats = now.hour or 24
        elif self.repeat == Rule.RepeatSettings.MINUTES15:
            repeats = now.minute // 15 or 4
        elif self.repeat == Rule.RepeatSettings.MINUTES30:
            repeats = now.minute // 30 or 2
        return repeats

    @property
    def midi(self) -> list[mido.Message]:
        """
        Returns the MIDI messages to play when the rule applies, taking into
        account the repeat setting.
        """
        if not self.song:
            return []
        return self.song.midi * self.number_repeats

    def get_absolute_url(self):
        return reverse("carillon:rules:detail", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        return self.name

    class Meta:
        ordering = ["-priority"]
        verbose_name = _("Rule")
        verbose_name_plural = _("Rules")

kampanile3/carillon/views/carillon.py
import json

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext as _
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from ..forms import CarillonForm
from ..models import Carillon


class CarillonListView(LoginRequiredMixin, ListView):
    model = Carillon

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "title": _("Carillons"),
                "subtitle": _("The following carillons are configured in the system:"),
            }
        )
        return context


class CarillonDetailView(LoginRequiredMixin, DetailView):
    model = Carillon

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "back_link": reverse("carillon:carillons:list"),
                "title": _("Carillon: %(name)s") % {"name": self.object.name},
            }
        )
        return context


class CarillonCreateView(LoginRequiredMixin, CreateView):
    model = Carillon
    form_class = CarillonForm
    template_name = "frontend/simple_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "back_link": reverse("carillon:carillons:list"),
                "title": _("Create carillon"),
                "subtitle": _("Add a carillon to play notes on."),
            }
        )
        return context


class CarillonUpdateView(LoginRequiredMixin, UpdateView):
    model = Carillon
    form_class = CarillonForm
    template_name = "frontend/simple_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "back_link": self.object.get_absolute_url(),
                "title": _("Modify carillon"),
                "subtitle": _("Modify the settings of the carillon: %(name)s")
                % {"name": self.object.name},
            }
        )
        return context


class CarillonDeleteView(LoginRequiredMixin, DeleteView):
    model = Carillon
    template_name = "frontend/confirm_delete.html"
    success_url = reverse_lazy("carillon:carillons:list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "back_link": reverse("carillon:carillons:list"),
                "title": _("Delete carillon"),
                "subtitle": _("Are you sure you want to delete carillon %(name)s?")
                % {"name": self.object.name},
            }
        )
        return context


@login_required
@csrf_exempt
def hit_note_view(request, pk):
    """Simple view to hit a note on a specific carillon."""
    if request.method != "POST":
        return JsonResponse({"error": "Only POST method allowed"}, status=405)

    try:
        carillon = get_object_or_404(Carillon, pk=pk)
        note = int(json.loads(request.body).get("note"))
        if note is None:
            return JsonResponse({"error": "Note parameter is required"}, status=400)
        if not (0 <= note <= 127):
            return JsonResponse({"error": "Note must be between 0 and 127"}, status=400)
        carillon.hit(note)
        return JsonResponse({"success": True, "carillon_id": pk, "note": note})
    except Exception as e:
        return JsonResponse({"error": str(e)}, status=500)


@login_required
@csrf_exempt
def stop_view(request, pk):
    """Simple view to stop the current song on a specific carillon."""
    if request.method != "POST":
        return JsonResponse({"error": "Only POST method allowed"}, status=405)

    try:
        carillon = get_object_or_404(Carillon, pk=pk)
        carillon.stop()
        return JsonResponse({"success": True, "carillon_id": pk})
    except Exception as e:
        return JsonResponse({"error": str(e)}, status=500)


@login_required
@csrf_exempt
def set_volume_view(request, pk):
    """Simple view to set the volume on a specific carillon."""
    if request.method != "POST":
        return JsonResponse({"error": "Only POST method allowed"}, status=405)

    try:
        carillon = get_object_or_404(Carillon, pk=pk)
        volume = int(json.loads(request.body).get("volume"))
        if volume is None:
            return JsonResponse({"error": "Volume parameter is required"}, status=400)
        if not (0 <= volume <= 127):
            return JsonResponse(
                {"error": "Volume must be between 0 and 127"}, status=400
            )
        carillon.volume = volume
        carillon.save()
        return JsonResponse({"success": True, "carillon_id": pk, "volume": volume})
    except Exception as e:
        return JsonResponse({"error": str(e)}, status=500)


@login_required
@csrf_exempt
def set_default_view(request, pk):
    """Simple view to set a carillon as the default carillon."""
    if request.method != "POST":
        return JsonResponse({"error": "Only POST method allowed"}, status=405)

    try:
        carillon = get_object_or_404(Carillon, pk=pk)
        carillon.default = True
        carillon.save()
        return JsonResponse({"success": True, "carillon_id": pk})
    except Exception as e:
        return JsonResponse({"error": str(e)}, status=500)


@login_required
@csrf_exempt
def toggle_active_view(request, pk):
    """Simple view to toggle the active state of a carillon."""
    if request.method != "POST":
        return JsonResponse({"error": "Only POST method allowed"}, status=405)

    try:
        carillon = get_object_or_404(Carillon, pk=pk)
        carillon.active = not carillon.active
        carillon.save()
        return JsonResponse(
            {"success": True, "carillon_id": pk, "active": carillon.active}
        )
    except Exception as e:
        return JsonResponse({"error": str(e)}, status=500)

kampanile3/carillon/templates/carillon/carillon_confirm_delete.html
{% extends "frontend/base.html" %}
{% load i18n %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <div class="row pt-3">
      <a href="{{ back_link }}" class="btn btn-outline-secondary col-5">
        {% trans "Cancel" %}
      </a>
      <input type="submit" class="btn btn-danger col-6 offset-1" value="{% trans "Confirm deletion" %}>
    </div>
  </form>
{% endblock %}

kampanile3/carillon/templates/carillon/carillon_detail.html
{% extends "frontend/base.html" %}
{% load i18n static %}

{% block subtitle %}
  {% if carillon.port_name %}
    {% blocktranslate with port=carillon.port_name %}The carillon is connected to port <code>{{ port }}</code>.{% endblocktranslate %}
  {% else %}
    {% blocktranslate %}The carillon is connected to the default port.{% endblocktranslate %}
  {% endif %}
{% endblock %}

{% block content %}
  {% url "carillon:carillons:update" carillon.pk as url %}
  {% include "frontend/includes/update_button.html" with label=_("Update carillon") %}

  {% if carillon.default %}
    <p class="lead">
      {% blocktranslate %}This is the default carillon.{% endblocktranslate %}
    </p>
  {% endif %}
  <p class="lead">
    {% if carillon.active %}
      {% blocktranslate %}The carillon is active.{% endblocktranslate %}
    {% else %}
      {% blocktranslate %}The carillon is currently <strong>not</strong> active.{% endblocktranslate %}
    {% endif %}
  </p>
  <p class="lead">
    {% blocktranslate with volume=carillon.volume %}The current volume is set to {{ volume }}.{% endblocktranslate %}
  </p>

  <h2>{% trans "Test sending MIDI-signals" %}</h2>
  <div class="btn-toolbar">
    <div class="piano-container btn-group me-2">
      <button type="button" class="btn btn-outline-primary" data-note="36">{% trans "C2" %}</button>
      <button type="button" class="btn btn-outline-primary" data-note="48">{% trans "C3" %}</button>
      <button type="button" class="btn btn-outline-primary" data-note="60">{% trans "C4" %}</button>
      <button type="button" class="btn btn-outline-primary" data-note="72">{% trans "C5" %}</button>
      <button type="button" class="btn btn-outline-primary" data-note="84">{% trans "C6" %}</button>
    </div>

    <div class="volume-container btn-group">
      <button type="button" class="btn btn-outline-secondary" data-volume="0">{% trans "Volume 0" %}</button>
      <button type="button" class="btn btn-outline-secondary" data-volume="63">{% trans "Volume 63" %}</button>
      <button type="button" class="btn btn-outline-secondary" data-volume="127">{% trans "Volume 127" %}</button>
    </div>
  </div>

  <div class="alert-placeholder mt-3"></div>
{% endblock %}

{% block extra_body %}
{{ block.super }}
<script src="{% static "frontend/alert_helper.js" %}"></script>
<script>
document.querySelectorAll('.piano-container button').forEach(button => {
  button.addEventListener('click', function() {
    const note = this.getAttribute('data-note');
    fetch(`{% url 'carillon:carillons:hit_note' carillon.pk %}`, {
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      body: JSON.stringify({note: note})
    })
    .then(response => response.json())
    .then(data => {
      let alert;
      if (data.success) {
        alert = generateAlert("{% blocktranslate %}Note played successfully!{% endblocktranslate %}", "success", 3000)
      } else {
        alert = generateAlert(`{% blocktranslate with error=data.error %}Error playing note: ${ data.error }{% endblocktranslate %}`, "success", 3000)
      }
      document.querySelector('.alert-placeholder').appendChild(alert);
    })
  });
});

document.querySelectorAll('.volume-container button').forEach(button => {
  button.addEventListener('click', function() {
    const volume = this.getAttribute('data-volume');
    fetch(`{% url 'carillon:carillons:set_volume' carillon.pk %}`, {
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      body: JSON.stringify({volume: volume})
    })
    .then(response => response.json())
    .then(data => {
      let alert;
      if (data.success) {
        alert = generateAlert("{% blocktranslate %}Volume set successfully!{% endblocktranslate %}", "success", 3000)
      } else {
        alert = generateAlert(`{% blocktranslate with error=data.error %}Error setting volume: ${ data.error }{% endblocktranslate %}`, "success", 3000)
      }
      document.querySelector('.alert-placeholder').appendChild(alert);
    })
  });
});
</script>
{% endblock %}

kampanile3/carillon/templates/carillon/carillon_form.html
{% extends "frontend/base.html" %}
{% load i18n crispy_forms_tags %}

{% block content %}
  {% crispy form %}
{% endblock %}

kampanile3/carillon/templates/carillon/carillon_list.html
{% extends "frontend/base.html" %}
{% load i18n %}

{% block content %}
  {% url "carillon:carillons:add" as url %}
  {% include "frontend/includes/add_button.html" with label=_("Add carillon") %}

  <table class="table">
    <thead>
      <tr>
        <th scope="col" title="{% translate "The default carillon?" %}" data-bs-toggle="tooltip">
          <span class="mdi mdi-star-outline"></span>
        </th>
        <th scope="col" title="{% translate "Is the carillon active?" %}" data-bs-toggle="tooltip">
          <span class="mdi mdi-bell-outline"></span>
        </th>
        <th scope="col" class="w-50">{% translate "Name" %}</th>
        <th scope="col" class="w-50">{% translate "Port Name" %}</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {% for carillon in carillon_list %}
        <tr>
          <td>
            {% if carillon.default %}
              <span class="mdi mdi-star" title="{% translate "This is the default carillon." %}" data-bs-toggle="tooltip"></span>
            {% endif %}
          </td>
          <td>
            {% if carillon.active %}
              <span class="mdi mdi-bell" title="{% translate "The carillon is active." %}" data-bs-toggle="tooltip"></span>
            {% else %}
              <span class="mdi mdi-bell-off" title="{% translate "The carillon is not active." %}" data-bs-toggle="tooltip"></span>
            {% endif %}
          </td>
          <th scope="row">
            <a href="{{ carillon.get_absolute_url }}">
              {{ carillon.name }}
            </a>
          </th>
          <td><code>{{ carillon.port_name }}</code></td>
          <td class="text-nowrap">
            {% url "carillon:carillons:update" carillon.pk as update_url %}
            {% url "carillon:carillons:delete" carillon.pk as delete_url %}
            {% include "frontend/includes/table_btn_group.html" with view_url=carillon.get_absolute_url %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

kampanile3/carillon/templates/carillon/confirm_delete.html
{% extends "frontend/base.html" %}
{% load i18n %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <div class="row pt-3">
      <a href="{{ back_link }}" class="btn btn-outline-secondary btn-lg col-5">
        {% trans "Cancel" %}
      </a>
      <input type="submit" class="btn btn-danger btn-lg col-6 offset-1" value="{% trans "Confirm deletion" %}">
    </div>
  </form>
{% endblock %}

kampanile3/carillon/templates/carillon/rule_detail.html
{% extends "frontend/base.html" %}
{% load i18n static %}

{% block content %}
  {% url "carillon:rules:update" rule.pk as url %}
  {% include "frontend/includes/update_button.html" with label=_("Update rule") %}

  <dl class="row mt-3">
    <dt class="col-sm-3">{% trans "Priority" %}</dt>
    <dd class="col-sm-9">{{ rule.priority }}</dd>
    <dt class="col-sm-3">{% trans "Cancel following rules" %}</dt>
    <dd class="col-sm-9">{{ rule.cancel_following|yesno:_("Yes,No") }}</dd>
    <dt class="col-sm-3">{% trans "Song" %}</dt>
    <dd class="col-sm-9">
      <a href="{{ rule.song.get_absolute_url }}">{{ rule.song.name }}</a>
    </dd>
    <dt class="col-sm-3">{% trans "Repeat" %}</dt>
    <dd class="col-sm-9">{{ rule.get_repeat_display }}</dd>
  </dl>

  <h2 class="mb-3">{% trans "Condition" %}</h2>
  {% include "./includes/rule_condition_render.html" with condition=rule.condition %}
{% endblock %}

kampanile3/carillon/templates/carillon/rule_list.html
{% extends "frontend/base.html" %}
{% load i18n %}

{% block content %}
  {% url "carillon:rules:add" as url %}
  {% include "frontend/includes/add_button.html" with label=_("Add rule") %}

  <table class="table">
    <thead>
      <tr>
        <th scope="col" class="w-50">{% translate "Name" %}</th>
        <th scope="col" class="w-50">{% translate "Song" %}</th>
        <th scope="col">
          <span class="mdi mdi-stop-circle-outline" title="{% translate "Cancel following rules" %}" data-bs-toggle="tooltip"></span>
        </th>
        <th scope="col">
          <span class="mdi mdi-exclamation-thick" title="{% translate "Priority" %}" data-bs-toggle="tooltip"></span>
        </th>
        <th scope="col">
          <span class="mdi mdi-repeat-variant" title="{% translate "Repeat" %}" data-bs-toggle="tooltip"></span>
        </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for rule in rule_list %}
        <tr>
          <th scope="row"><a href="{{ rule.get_absolute_url }}">{{ rule.name }}</a></th>
          <td>{{ rule.song.name }}</td>
          <td class="text-nowrap">
            {% if rule.cancel_following %}
              <span class="mdi mdi-check" title="{% translate "Cancel following rules" %}" data-bs-toggle="tooltip"></span>
            {% else %}
              <span class="mdi mdi-close" title="{% translate "Do not cancel following rules" %}" data-bs-toggle="tooltip"></span>
            {% endif %}
          </td>
          <td class="text-nowrap">{{ rule.priority }}</td>
          <td class="text-nowrap">
            {% if rule.repeat == "o" %}
              {% include "carillon/includes/rule_repeat_icon.html" with icon="circle-outline" %}
            {% elif rule.repeat == "h12" %}
              {% include "carillon/includes/rule_repeat_icon.html" with icon="hours-12" %}
            {% elif rule.repeat == "h24" %}
              {% include "carillon/includes/rule_repeat_icon.html" with icon="hours-24" %}
            {% elif rule.repeat == "m15" %}
              {% include "carillon/includes/rule_repeat_icon.html" with icon="clock-time-three-outline" %}
            {% elif rule.repeat == "m30" %}
              {% include "carillon/includes/rule_repeat_icon.html" with icon="clock-time-six-outline" %}
            {% else %}
              {% include "carillon/includes/rule_repeat_icon.html" %}
            {% endif %}
          </td>
          <td class="text-nowrap">
            {% url "carillon:rules:update" rule.pk as update_url %}
            {% url "carillon:rules:delete" rule.pk as delete_url %}
            {% include "frontend/includes/table_btn_group.html" with view_url=rule.get_absolute_url %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

kampanile3/carillon/templates/carillon/simple_form.html
{% extends "frontend/base.html" %}
{% load i18n crispy_forms_tags %}

{% block content %}
  {% crispy form %}
{% endblock %}

kampanile3/carillon/templates/carillon/striker_detail.html
{% extends "frontend/base.html" %}
{% load i18n static %}

{% block content %}
  {% url "carillon:strikers:update" striker.pk as url %}
  {% include "frontend/includes/update_button.html" with label=_("Update striker") %}

  <dl class="row mt-3">
    <dt class="col-sm-3">{% trans "Carillon" %}</dt>
    <dd class="col-sm-9">
      <a href="{{ striker.carillon.get_absolute_url }}">{{ striker.carillon.name }}</a>
    </dd>
    <dt class="col-sm-3">{% trans "Priority" %}</dt>
    <dd class="col-sm-9">{{ striker.priority }}</dd>
  </dl>

  <h2 class="mb-3">{% trans "Rules" %}</h2>
  {% url "carillon:strikers:add_rule" striker.pk as url %}
  {% include "frontend/includes/add_button.html" with label=_("Add rule") %}

  {% if rule_list %}
    <table class="table">
      <thead>
        <tr>
          <th scope="col" class="w-50">{% translate "Name" %}</th>
          <th scope="col" class="w-50">{% translate "Song" %}</th>
          <th scope="col">
            <span class="mdi mdi-stop-circle-outline" title="{% translate "Cancel following rules" %}" data-bs-toggle="tooltip"></span>
          </th>
          <th scope="col">
            <span class="mdi mdi-exclamation-thick" title="{% translate "Priority" %}" data-bs-toggle="tooltip"></span>
          </th>
          <th scope="col">
            <span class="mdi mdi-repeat-variant" title="{% translate "Repeat" %}" data-bs-toggle="tooltip"></span>
          </th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for rule in rule_list %}
          <tr>
            <th scope="row"><a href="{{ rule.get_absolute_url }}">{{ rule.name }}</a></th>
            <td>{{ rule.song.name }}</td>
            <td class="text-nowrap">
              {% if rule.cancel_following %}
                <span class="mdi mdi-check" title="{% translate "Cancel following rules" %}" data-bs-toggle="tooltip"></span>
              {% else %}
                <span class="mdi mdi-close" title="{% translate "Do not cancel following rules" %}" data-bs-toggle="tooltip"></span>
              {% endif %}
            </td>
            <td class="text-nowrap">{{ rule.priority }}</td>
            <td class="text-nowrap">
              {% if rule.repeat == "o" %}
                {% include "carillon/includes/rule_repeat_icon.html" with icon="circle-outline" %}
              {% elif rule.repeat == "h12" %}
                {% include "carillon/includes/rule_repeat_icon.html" with icon="hours-12" %}
              {% elif rule.repeat == "h24" %}
                {% include "carillon/includes/rule_repeat_icon.html" with icon="hours-24" %}
              {% elif rule.repeat == "m15" %}
                {% include "carillon/includes/rule_repeat_icon.html" with icon="clock-time-three-outline" %}
              {% elif rule.repeat == "m30" %}
                {% include "carillon/includes/rule_repeat_icon.html" with icon="clock-time-six-outline" %}
              {% else %}
                {% include "carillon/includes/rule_repeat_icon.html" %}
              {% endif %}
            </td>
            <td class="text-nowrap">
              {% url "carillon:rules:update" rule.pk as update_url %}
              {% url "carillon:rules:delete" rule.pk as delete_url %}
              {% include "frontend/includes/table_btn_group.html" with view_url=rule.get_absolute_url %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p class="lead">
      {% blocktranslate %}There are no rules for this striker yet.{% endblocktranslate %}
    </p>
  {% endif %}

{% endblock %}