kampanile3/frontend/urls.py
from django.urls import path

from .views import IndexView

app_name = "frontend"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
]

kampanile3/gpio/urls.py
from django.urls import include, path

from . import views

app_name = "gpio"
urlpatterns = [
    path(
        "inputs/",
        include(
            (
                [
                    path("", views.InputListView.as_view(), name="list"),
                    path("add/", views.InputCreateView.as_view(), name="add"),
                    path("<int:pk>/", views.InputDetailView.as_view(), name="detail"),
                    path(
                        "<int:pk>/update/",
                        views.InputUpdateView.as_view(),
                        name="update",
                    ),
                    path(
                        "<int:pk>/delete/",
                        views.InputDeleteView.as_view(),
                        name="delete",
                    ),
                ],
                "inputs",
            )
        ),
    )
]

kampanile3/kampanile3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("frontend.urls")),
    path("carillon/", include("carillon.urls")),
    path("gpio/", include("gpio.urls")),
]

kampanile3/frontend/forms.py
from crispy_forms.layout import HTML, Div, Layout, Submit
from django.utils.translation import gettext as _


class FormAction(Layout):
    def __init__(
        self, cancel_url=None, cancel_label=_("Cancel"), submit_label=_("Save")
    ):
        super().__init__(
            Div(
                Div(
                    HTML(
                        f"<a href='{cancel_url}' class='btn btn-outline-secondary d-block'>{cancel_label}</a>"
                    ),
                    css_class="col-5 col-sm-3 offset-sm-5",
                ),
                Div(
                    Submit("save", submit_label, css_class="d-block w-100"),
                    css_class="col-6 offset-1 offset-sm-0 col-sm-4",
                ),
                css_class="row gx-2 mb-3",
            )
        )

kampanile3/frontend/views.py
from carillon.models import Carillon, Rule, Song, Striker
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext as _
from django.views.generic import TemplateView


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = "frontend/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "title": _("Overview"),
                "subtitle": _("Welcome to your carillon management interface!"),
                "carillons": Carillon.objects.all(),
                "sample_songs": Song.objects.order_by("-id")[:4],
                "num_songs": Song.objects.count(),
                "num_rules": Rule.objects.count(),
                "num_strikers": Striker.objects.count(),
                "default_carillon": Carillon.get_default(),
            }
        )
        return context

kampanile3/frontend/templates/frontend/base.html
{% load i18n static %}
{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Kampanile{% endblock %}</title>
    <link rel="icon" href="{% static "favicon.svg" %}">

    <link rel="stylesheet" href="{% static "bootstrap/dist/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "@mdi/font/css/materialdesignicons.min.css" %}">
    {% block extra_head %}{% endblock %}
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
      <div class="container-md">
        <a class="navbar-brand" href="{% url "frontend:index" %}"><i class="mdi mdi-bell-outline"></i> Kampanile</a>
        {% if user.is_authenticated %}
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link{% if app_name == "carillon:carillons" %} active{% endif %}" href="{% url 'carillon:carillons:list' %}">
                  {% trans "Carillons" %}
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link{% if app_name == "carillon:strikers" %} active{% endif %}" href="{% url 'carillon:strikers:list' %}">
                  {% trans "Strikers" %}
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link{% if app_name == "carillon:songs" %} active{% endif %}" href="{% url 'carillon:songs:list' %}">
                  {% trans "Songs" %}
                </a>
              </li>
              {% if GPIO_ENABLED %}
                <li class="nav-item">
                  <a class="nav-link{% if app_name == "gpio:inputs" %} active{% endif %}" href="{% url 'gpio:inputs:list' %}">
                    {% trans "GPIO-Inputs" %}
                  </a>
                </li>
              {% endif %}
            </ul>
          </div>
          <div class="dropdown">
            <button class="btn btn-outline-light btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown">
              <span class="mdi mdi-account-outline"></span>
              {{ user.username }}
            </button>
            <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end">
              <li>
                <a class="dropdown-item" href="{% url 'password_change' %}">
                  <span class="mdi mdi-lock"></span>
                  {% trans "Change password" %}
                </a>
              </li>
              {% if user.is_superuser %}
                <li>
                  <a class="dropdown-item" href="{% url 'admin:index' %}">
                    <span class="mdi mdi-shield-account"></span>
                    {% trans "Administration" %}
                  </a>
                </li>
                <li><hr class="dropdown-divider"></li>
              {% endif %}
              <li>
                <form method="post" action="{% url 'logout' %}">
                  {% csrf_token %}
                  <button type="submit" class="dropdown-item">
                    <span class="mdi mdi-logout"></span>
                    {% trans "Logout" %}
                  </button>
                </form>
              </li>
            </ul>
          </div>
        {% endif %}
      </div>
    </nav>

    <div class="container-md py-3">
      {% block header %}
        <h1>
          {% if back_link %}
            <a href="{{ back_link }}" class="btn btn-outline-secondary me-2 rounded-circle">
              <span class="mdi mdi-arrow-left"></span>
            </a>
          {% endif %}
          {{ title }}
        </h1>
        <p class="lead">{% block subtitle %}{{ subtitle }}{% endblock %}</p>
      {% endblock %}
      {% block content %}{% endblock %}
    </div>

    <script src="{% static "bootstrap/dist/js/bootstrap.bundle.min.js" %}"></script>
    <script>
      var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
      var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
        return new bootstrap.Tooltip(tooltipTriggerEl)
      })
    </script>
    {% block extra_body %}{% endblock %}
  </body>
</html>

kampanile3/frontend/templates/frontend/confirm_delete.html
{% extends "./base.html" %}
{% load i18n %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <div class="row pt-3">
      <a href="{{ back_link }}" class="btn btn-outline-secondary btn-lg col-5">
        {% trans "Cancel" %}
      </a>
      <input type="submit" class="btn btn-danger btn-lg col-6 offset-1" value="{% trans "Confirm deletion" %}">
    </div>
  </form>
{% endblock %}

kampanile3/frontend/templates/frontend/index.html
{% extends "./base.html" %}
{% load i18n static %}

{% block content %}
  <div class="row row-cols-1 row-cols-md-2 row-cols-xl-3 g-4">

    <div class="col">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title">
            <span class="mdi mdi-chart-box-outline"></span>
            {% trans "Statistics" %}
          </h5>
          <h6 class="card-subtitle mb-2 text-muted">
            {% trans "Your setup in numbers" %}
          </h6>
          <p class="card-text">
            {% blocktranslate %}The main parameters of your carillon are summarized here.{% endblocktranslate %}
          </p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <span class="mdi mdi-bell-ring-outline"></span>
            {% blocktrans count num=carillons.count %}{{ num }} carillon{% plural %}{{ num }} carillons{% endblocktrans %}
          </li>
          <li class="list-group-item">
            <span class="mdi mdi-alarm-multiple"></span>
            {% blocktrans count num=num_strikers %}{{ num }} striker{% plural %}{{ num }} strikers{% endblocktrans %}
          </li>
          <li class="list-group-item">
            <span class="mdi mdi-list-status"></span>
            {% blocktrans count num=num_rules %}{{ num }} rule{% plural %}{{ num }} rules{% endblocktrans %}
          </li>
          <li class="list-group-item">
            <span class="mdi mdi-music"></span>
            {% blocktrans count num=num_songs %}{{ num }} song{% plural %}{{ num }} songs{% endblocktrans %}
          </li>
        </ul>
      </div>
    </div>

    <div class="col">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title">
            <span class="mdi mdi-file-music-outline"></span>
            {% trans "Songs" %}
          </h5>
          <h6 class="card-subtitle mb-2 text-muted">
            {% trans "Your most recent songs" %}
          </h6>
          <p class="card-text">
            {% blocktranslate %}A quick way to play your most recent additions to your song library:{% endblocktranslate %}
          </p>
        </div>
        <ul class="list-group list-group-flush" id="songs-list">
          {% for song in sample_songs %}
            <li class="list-group-item">
              <button class="btn btn-outline-primary btn-sm me-2" title="{% trans "Play song now" %}" data-bs-toggle="tooltip" data-action="play" data-song="{{ song.id }}">
                <span class="mdi mdi-play"></span>
              </button>
              <span>{{ song.name }}</span>
              <a href="{% url 'carillon:songs:detail' song.id %}" class="btn btn-outline-secondary btn-sm float-end" title="{% trans "View details" %}" data-bs-toggle="tooltip">
                <span class="mdi mdi-arrow-right"></span>
              </a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>

    <div class="col">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title">
            <span class="mdi mdi-bell-outline"></span>
            {% trans "Carillons" %}
          </h5>
          <h6 class="card-subtitle mb-2 text-muted">
            {% trans "Summary of all your carillons" %}
          </h6>
          <p class="card-text">
            {% blocktranslate %}The most important settings about your carillons:{% endblocktranslate %}
          </p>
        </div>
        <ul class="list-group list-group-flush" id="carillons-list">
          {% for carillon in carillons %}
            <li class="list-group-item">
              <div class="btn-group btn-group-sm me-2">
                <button class="btn btn-outline-primary" title="{% trans "Set as default carillon" %}" data-bs-toggle="tooltip" data-action="default" data-carillon="{{ carillon.id }}">
                  <span class="mdi mdi-star{% if not carillon.default %}-outline{% endif %}"></span>
                </button>
                <button class="btn btn-outline-primary" title="{% trans "Toggle activation of carillon" %}" data-bs-toggle="tooltip" data-action="active" data-carillon="{{ carillon.id }}">
                  <span class="mdi mdi-bell{% if not carillon.active %}-off-outline{% endif %}"></span>
                </button>
              </div>
              <span>{{ carillon.name }}</span>
              <a href="{% url 'carillon:carillons:detail' carillon.id %}" class="btn btn-outline-secondary btn-sm float-end" title="{% trans "View details" %}" data-bs-toggle="tooltip">
                <span class="mdi mdi-arrow-right"></span>
              </a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
    <div class="col">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title">
            <span class="mdi mdi-bell-cog-outline"></span>
            {% trans "Main settings" %}
          </h5>
          <h6 class="card-subtitle mb-2 text-muted">
            {% trans "Controlling the default carillon" %}
          </h6>
          <p class="card-text">
            {% blocktranslate %}Here you are able to control the main parameters of the default carillon:{% endblocktranslate %}
          </p>
          <div class="row">
            <div class="col">
              <label for="volume-range" class="form-label">
                {% trans "Volume" %}
              </label>
              <input type="range" class="form-range" id="volume-range" min="0" max="127" step="1" value="{{ default_carillon.volume }}">
            </div>
            <div class="col-auto d-flex align-items-center">
              <button class="btn btn-outline-primary" title="{% trans "Stop playing" %}" data-bs-toggle="tooltip" id="stop-button">
                <span class="mdi mdi-stop"></span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

  <div class="position-fixed bottom-0 end-0 p-3" style="z-index: 11">
    <div id="alert-placeholder"></div>
  </div>
{% endblock %}

{% block extra_body %}
{{ block.super }}
<script src="{% static "frontend/alert_helper.js" %}"></script>
<script>
document.getElementById("carillons-list").querySelectorAll("button").forEach(button => {
  button.addEventListener('click', event => {
    const carillonId = button.getAttribute('data-carillon')
    const action = button.getAttribute('data-action')
    button.disabled = true
    let url = action === 'default' ?
      `{% url "carillon:carillons:set_default" 1234 %}` :
      `{% url "carillon:carillons:toggle_active" 1234 %}`
    url = url.replace('1234', carillonId)
    fetch(url, {
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
    })
    .then(response => response.json())
    .then(data => {
      if (data.success) window.location.reload()
      else {
        document.getElementById('alert-placeholder').appendChild(
          generateAlert(`{% blocktranslate %}Error: ${ data.error }{% endblocktranslate %}`, "danger")
        )
        button.disabled = false
      }
    })
  })
})

document.getElementById("songs-list").querySelectorAll("button").forEach(button => {
  button.addEventListener('click', event => {
    const songId = button.getAttribute('data-song')
    button.disabled = true
    fetch(`{% url "carillon:songs:play" 1234 %}`.replace("1234", songId), {
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      body: JSON.stringify({ carillon_id: {{ default_carillon.id }} }),
    })
    .then(response => response.json())
    .then(data => {
      if (!data.success) {
        document.getElementById('alert-placeholder').appendChild(
          generateAlert(`{% blocktranslate %}Error: ${ data.error }{% endblocktranslate %}`, "danger")
        )
      }
      button.disabled = false
    })
  })
})

document.getElementById("volume-range").addEventListener('change', event => {
  const volume = parseInt(event.target.value)
  fetch(`{% url "carillon:carillons:set_volume" 1234 %}`.replace("1234", {{ default_carillon.id }}), {
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    body: JSON.stringify({ volume: volume }),
  })
  .then(response => response.json())
  .then(data => {
    if (!data.success) {
      document.getElementById('alert-placeholder').appendChild(
        generateAlert(`{% blocktranslate %}Error: ${ data.error }{% endblocktranslate %}`, "danger")
      )
    }
  })
})

document.getElementById("stop-button").addEventListener('click', event => {
  fetch(`{% url "carillon:carillons:stop" 1234 %}`.replace("1234", {{ default_carillon.id }}), {
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
  })
  .then(response => response.json())
  .then(data => {
    if (!data.success) {
      document.getElementById('alert-placeholder').appendChild(
        generateAlert(`{% blocktranslate %}Error: ${ data.error }{% endblocktranslate %}`, "danger")
      )
    }
  })
})
</script>
{% endblock %}

kampanile3/frontend/templates/frontend/simple_form.html
{% extends "./base.html" %}
{% load i18n crispy_forms_tags %}

{% block content %}
  {% crispy form %}
{% endblock %}